# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pairing_algorithm <- function(keys1, values1, keys2, values2) {
    .Call(`_StableMarriage2_pairing_algorithm`, keys1, values1, keys2, values2)
}

